### ISSUE TITLE
Hash syntax 

### ISSUE THREAD

**Issue by michal-samluk** [codequest-eu/codeguard#18]
Which syntax we should prefer, and why? 
```ruby
{ key: 'value' } 
```
or 
```ruby
{key: 'value'}
```

I think we should go with the first solution. It looks it is much more popular in ruby community.

**Comment by kruszczynski** [comment]
I prefer the second solution. Purely subjectively though so I will adapt to whatever majority prefers

**Comment by ja999** [comment]
It's more popular and it seems easier to read. :) I vote for #1.

**Comment by Xypus** [comment]
Personally I'd go with the second one and leave spacings only for blocks. It is much easier to write with less spaces to worry about.

**Comment by mikolajgrzyb** [comment]
Maybe lets do what rubymine is doing with with autoformating? It reserves spaces for blocks.

**Comment by aberracja** [comment]
I prefer first because it's easier to read for me. No1!

**Comment by PatrykTyszka** [comment]
I prefer the first one. In my opinion is more readable, same as syntax a = 2 instead a=2.

**Comment by PiotrekProtas** [comment]
IMO #1 easier to read :]

**Comment by MagdaMalinowska** [comment]
Vote for 1. Same reason as most of you- easier to read

**Comment by pawelkondraciuk** [comment]
In my opinion 1st looks cleaner and easier to read.

**Comment by grodowski** [comment]
I'd definitely go for #2. To me it looks like a standard in all community projects!

**Comment by michal-samluk** [comment]
Just FYI: 
Rails ActiveModel is using No.1 syntax: https://github.com/rails/rails/blob/master/activemodel/lib/active_model/naming.rb#L188

**Comment by michal-samluk** [comment]
I think that RubyMine argument is not actually good. We are using Rubocop now - and indentation for RubyMine in many cases is already different from Rubocop. Making auto-formatting in RubyMine is currently pointless - because it may break recommended indentation of Rubocop. 

In Rubocop we can easilly autoformat using: `rubocop -a path/to/my/file.rb`.

**Comment by michal-samluk** [comment]
BTW: 
https://github.com/bbatsov/ruby-style-guide#spaces-operators
>
The first variant is slightly more readable (and arguably more popular in the Ruby community in general). The second variant has the advantage of adding visual difference between block and hash literals. Whichever one you pick - apply it consistently.

**Comment by BartlomiejSkwira** [comment]
#1 has my vote

**Comment by andrzejtrzaska** [comment]
#1

**Comment by torrocus** [comment]
Ruby community prefer 1st, and I too. https://github.com/styleguide/ruby

Thoughtbot uses this style also: https://github.com/thoughtbot/guides/tree/master/style/ruby

**Comment by torrocus** [comment]
The result of voting:

- 11 votes on 1st
- 3 votes on 2nd

Now you only need to change `.rubocop.yml`:
```
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
```

**Comment by pjar** [comment]
Number 1 is easier to read but it's good have distinction between blocks and hashes - I guess it was always that we use around spaces for blocks and no spaces for hashes. Then you see what is what at first glance. 

Vote #2  for hashes.

**Comment by marcinwyszynski** [comment]
[Please kindly stop spending time on non-issues.](https://en.wikipedia.org/wiki/Parkinson%27s_law_of_triviality)

**Comment by torrocus** [comment]
The simplest way is to use the default settings of rubocop and other linters. You decide to change these settings. My proposition of `.rubocop.yml` is
```
AllCops:
  Exclude:
    - bin/*
    - db/**/*
```

**Comment by marcinwyszynski** [comment]
Default settings may change and have indeed changed over time. By freezing settings you avoid situations where a change in `$yourLinter`'s version causes CI to suddenly start failing. This again has already been discussed when we introduced style guides at code quest.

I would like to point out that this discussion is trivial and counterproductive. In the future if we're to organise polls like this three questions should be asked:

1. what's your preference?
2. do you feel so strongly about your preference that you're willing to spend non-trivial amount of time changing your code to conform to it?
3. do you feel so strongly about it that you want every last engineer in your company spend non-trivial amount of time changing __their__ code to conform to __your__ preference?

If the answer to 3 is a YES you'd better have a bloody good argument and _because I like it better_ ain't one. In other words please try to think how your preferences would impact your immediate team and the company as a whole.

I'm going to close this discussion. If you feel upset about it please chat me up in person and I'll happily explain my position.
